// Code generated by ent, DO NOT EDIT.

package ent

import (
	"MSaaS-Framework/MSaaS/cmd/wizcraft/app/ent/apispec"
	"MSaaS-Framework/MSaaS/cmd/wizcraft/app/ent/database"
	"MSaaS-Framework/MSaaS/cmd/wizcraft/app/ent/generalspec"
	"MSaaS-Framework/MSaaS/cmd/wizcraft/app/ent/project"
	"MSaaS-Framework/MSaaS/cmd/wizcraft/app/ent/schema"
	"MSaaS-Framework/MSaaS/cmd/wizcraft/app/ent/service"
	"MSaaS-Framework/MSaaS/cmd/wizcraft/app/ent/user"
	"MSaaS-Framework/MSaaS/cmd/wizcraft/app/ent/usergeneralspecpermissions"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	apispecFields := schema.APISpec{}.Fields()
	_ = apispecFields
	// apispecDescID is the schema descriptor for id field.
	apispecDescID := apispecFields[0].Descriptor()
	// apispec.DefaultID holds the default value on creation for the id field.
	apispec.DefaultID = apispecDescID.Default.(func() uuid.UUID)
	databaseFields := schema.Database{}.Fields()
	_ = databaseFields
	// databaseDescConnectionPath is the schema descriptor for connection_path field.
	databaseDescConnectionPath := databaseFields[1].Descriptor()
	// database.ConnectionPathValidator is a validator for the "connection_path" field. It is called by the builders before save.
	database.ConnectionPathValidator = databaseDescConnectionPath.Validators[0].(func(string) error)
	// databaseDescDbType is the schema descriptor for db_type field.
	databaseDescDbType := databaseFields[3].Descriptor()
	// database.DbTypeValidator is a validator for the "db_type" field. It is called by the builders before save.
	database.DbTypeValidator = databaseDescDbType.Validators[0].(func(string) error)
	// databaseDescID is the schema descriptor for id field.
	databaseDescID := databaseFields[0].Descriptor()
	// database.DefaultID holds the default value on creation for the id field.
	database.DefaultID = databaseDescID.Default.(func() uuid.UUID)
	generalspecFields := schema.GeneralSpec{}.Fields()
	_ = generalspecFields
	// generalspecDescUUID is the schema descriptor for uuid field.
	generalspecDescUUID := generalspecFields[0].Descriptor()
	// generalspec.DefaultUUID holds the default value on creation for the uuid field.
	generalspec.DefaultUUID = generalspecDescUUID.Default.(func() uuid.UUID)
	// generalspecDescStatus is the schema descriptor for status field.
	generalspecDescStatus := generalspecFields[4].Descriptor()
	// generalspec.DefaultStatus holds the default value on creation for the status field.
	generalspec.DefaultStatus = generalspecDescStatus.Default.(string)
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescID is the schema descriptor for id field.
	projectDescID := projectFields[0].Descriptor()
	// project.DefaultID holds the default value on creation for the id field.
	project.DefaultID = projectDescID.Default.(func() uuid.UUID)
	serviceFields := schema.Service{}.Fields()
	_ = serviceFields
	// serviceDescID is the schema descriptor for id field.
	serviceDescID := serviceFields[0].Descriptor()
	// service.DefaultID holds the default value on creation for the id field.
	service.DefaultID = serviceDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.DefaultName holds the default value on creation for the name field.
	user.DefaultName = userDescName.Default.(string)
	// userDescActive is the schema descriptor for active field.
	userDescActive := userFields[6].Descriptor()
	// user.DefaultActive holds the default value on creation for the active field.
	user.DefaultActive = userDescActive.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[7].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[8].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	usergeneralspecpermissionsFields := schema.UserGeneralSpecPermissions{}.Fields()
	_ = usergeneralspecpermissionsFields
	// usergeneralspecpermissionsDescID is the schema descriptor for id field.
	usergeneralspecpermissionsDescID := usergeneralspecpermissionsFields[0].Descriptor()
	// usergeneralspecpermissions.DefaultID holds the default value on creation for the id field.
	usergeneralspecpermissions.DefaultID = usergeneralspecpermissionsDescID.Default.(func() uuid.UUID)
}
