// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// APISpec is the predicate function for apispec builders.
type APISpec func(*sql.Selector)

// Database is the predicate function for database builders.
type Database func(*sql.Selector)

// GeneralSpec is the predicate function for generalspec builders.
type GeneralSpec func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// Service is the predicate function for service builders.
type Service func(*sql.Selector)

// Token is the predicate function for token builders.
type Token func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserGeneralSpecPermissions is the predicate function for usergeneralspecpermissions builders.
type UserGeneralSpecPermissions func(*sql.Selector)
